export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST"
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"